<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.0.1</Version>
    <FileVersion>0.0.1.0</FileVersion>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
    <None Include="models\sensevoice\model_quant.onnx" CopyToOutputDirectory="PreserveNewest" />
    <None Include="models\sensevoice\tokens.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="models\sensevoice\am.mvn" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Markdig" Version="0.37.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.0" />
    <PackageReference Include="QuestPDF" Version="2024.12.0" />
  </ItemGroup>
</Project>
